// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADgUuhB6HAPgHm-LR3HVgG6Yn7dmC6C9g',
    appId: '1:41722186933:web:84e4b5584d7e48770cc2fc',
    messagingSenderId: '41722186933',
    projectId: 'meetupapp-6e350',
    authDomain: 'meetupapp-6e350.firebaseapp.com',
    storageBucket: 'meetupapp-6e350.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHy_Ud4PRnLIU4OWiC63MXV79tkAYrimQ',
    appId: '1:41722186933:android:28473928067a26210cc2fc',
    messagingSenderId: '41722186933',
    projectId: 'meetupapp-6e350',
    storageBucket: 'meetupapp-6e350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9XulG31tTXxcPw6wq_4pKWxReXwlb3RA',
    appId: '1:41722186933:ios:eba96266b2cb11420cc2fc',
    messagingSenderId: '41722186933',
    projectId: 'meetupapp-6e350',
    storageBucket: 'meetupapp-6e350.appspot.com',
    iosClientId: '41722186933-t0og1g9rm0nr50ejfj99ksu62biuqg6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9XulG31tTXxcPw6wq_4pKWxReXwlb3RA',
    appId: '1:41722186933:ios:eba96266b2cb11420cc2fc',
    messagingSenderId: '41722186933',
    projectId: 'meetupapp-6e350',
    storageBucket: 'meetupapp-6e350.appspot.com',
    iosClientId: '41722186933-t0og1g9rm0nr50ejfj99ksu62biuqg6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
